import GLOBAL_VAR from '../../globals.json';
const ENV_VAR = {
  ANDROID_CLIENT_ID: __DEV__ ? GLOBAL_VAR.ANDROID_CLIENT_ID : GLOBAL_VAR.ANDROID_RELEASE_CLIENT_ID,
  BACKEND_URL: __DEV__ ? GLOBAL_VAR.BACKEND_URL_DEV : GLOBAL_VAR.BACKEND_URL_PROD,
};
export default ENV_VAR;
